from pygame import *
width,height=1200,703
screen=display.set_mode((width,height))
tileDict = {
    "d1" : image.load("Textures\\png\\Tiles\\d1.png").convert_alpha(),
    "d2" : image.load("Textures\\png\\Tiles\\d2.png").convert_alpha(),
    "d3" : image.load("Textures\\png\\Tiles\\d3.png").convert_alpha(),
    "d4" : image.load("Textures\\png\\Tiles\\d4.png").convert_alpha(),
    "d5" : image.load("Textures\\png\\Tiles\\d5.png").convert_alpha(),
    "d6" : image.load("Textures\\png\\Tiles\\d6.png").convert_alpha(),
    "d7" : image.load("Textures\\png\\Tiles\\d7.png").convert_alpha(),
    "d8" : image.load("Textures\\png\\Tiles\\d8.png").convert_alpha(),
    "d9" : image.load("Textures\\png\\Tiles\\d9.png").convert_alpha(),
    "da" : image.load("Textures\\png\\Tiles\\da.png").convert_alpha(),
    "db" : image.load("Textures\\png\\Tiles\\db.png").convert_alpha(),
    "dc" : image.load("Textures\\png\\Tiles\\dc.png").convert_alpha(),
    "t_l_side_dirt" : image.load("Textures\\png\\Tiles\\t_l_side_dirt.png").convert_alpha(),
    "t_m_side_dirt" : image.load("Textures\\png\\Tiles\\dirt.png").convert_alpha(),
    "t_r_side_dirt" : image.load("Textures\\png\\Tiles\\t_r_side_dirt.png").convert_alpha(),
    "m_r_side_dirt" : image.load("Textures\\png\\Tiles\\m_r_side_dirt.png").convert_alpha(),
    "m_l_side_dirt" : image.load("Textures\\png\\Tiles\\m_l_side_dirt.png").convert_alpha(),
    "m_m_side_dirt" : image.load("Textures\\png\\Tiles\\m_dirt.png").convert_alpha(),
    "b_r_side_dirt" : image.load("Textures\\png\\Tiles\\b_r_side_dirt.png").convert_alpha(),
    "b_l_side_dirt" : image.load("Textures\\png\\Tiles\\b_l_side_dirt.png").convert_alpha(),
    "b_m_side_dirt" : image.load("Textures\\png\\Tiles\\b_m_side_dirt.png").convert_alpha(),
    "p_l_side_dirt" : image.load("Textures\\png\\Tiles\\p_l_side_dirt.png").convert_alpha(),
    "p_m_side_dirt" : image.load("Textures\\png\\Tiles\\p_m_side_dirt.png").convert_alpha(),
    "p_r_side_dirt" : image.load("Textures\\png\\Tiles\\p_r_side_dirt.png").convert_alpha(),
    "door1" : image.load("Textures\\png\\Door\\door1.png").convert_alpha(),
    "door2" : image.load("Textures\\png\\Door\\door2.png").convert_alpha(),
    "door3" : image.load("Textures\\png\\Door\\door3.png").convert_alpha(),
    "door4" : image.load("Textures\\png\\Door\\door4.png").convert_alpha(),
    "question_fire_flower" : image.load("Textures\\png\\Tiles\\block1.png").convert_alpha(),
    "question_gun" : image.load("Textures\\png\\Tiles\\block1.png").convert_alpha(),
    "Tree_2": image.load("Textures\png\Object\Tree_2.png"),
    "fire_flower" : image.load("Textures\png\Tiles\\fire_flower.png").convert_alpha(),
    "neutral_block" : image.load("Textures\png\Tiles\\neutral_block.png").convert_alpha(),
    "Bush (1)" : image.load("Textures\png\Object\Bush (1).png").convert_alpha(),
    "Bush (2)" : image.load("Textures\png\Object\Bush (2).png").convert_alpha(),
    "Bush (3)" : image.load("Textures\png\Object\Bush (3).png").convert_alpha(),
    "Bush (4)" : image.load("Textures\png\Object\Bush (4).png").convert_alpha(),
    "BlueSlime1Left": image.load("Textures\png\Enemies\BlueSlime1Left.png").convert_alpha(),
    "BlueSlime2Left": image.load("Textures\png\Enemies\BlueSlime2Left.png").convert_alpha(),
    "BlueSlimeSqLeft": image.load("Textures\png\Enemies\BlueSlimeSqLeft.png").convert_alpha(),
    "BlueSlimeDeadLeft": image.load("Textures\png\Enemies\BlueSlimeDeadLeft.png").convert_alpha(),
    "PinkSlime1Left": image.load("Textures\png\Enemies\PinkSlime1Left.png").convert_alpha(),
    "PinkSlime2Left": image.load("Textures\png\Enemies\PinkSlime2Left.png").convert_alpha(),
    "PinkSlimeSqLeft": image.load("Textures\png\Enemies\PinkSlimeSqLeft.png").convert_alpha(),
    "PinkSlimeDeadLeft": image.load("Textures\png\Enemies\PinkSlimeDeadRight.png").convert_alpha(),
    "BlueSlimeDeaDeadLeft" : image.load("Textures\png\Enemies\BlueSlimeDeadLeft.png").convert_alpha(),
    "PinkSlimeDeaDeadLeft" : image.load("Textures\png\Enemies\PinkSlimeDeadLeft.png").convert_alpha(),                                                                                                 
    "BlueSlime1Right": image.load("Textures\png\Enemies\BlueSlime1Right.png").convert_alpha(),
    "BlueSlime2Right": image.load("Textures\png\Enemies\BlueSlime2Right.png").convert_alpha(),
    "BlueSlimeSqRight": image.load("Textures\png\Enemies\BlueSlimeSqRight.png").convert_alpha(),
    "BlueSlimeDeadRight": image.load("Textures\png\Enemies\BlueSlimeDeadRight.png").convert_alpha(),
    "PinkSlime1Right": image.load("Textures\png\Enemies\PinkSlime1Right.png").convert_alpha(),
    "PinkSlime2Right": image.load("Textures\png\Enemies\PinkSlime2Right.png").convert_alpha(),
    "PinkSlimeSqRight": image.load("Textures\png\Enemies\PinkSlimeSqRight.png").convert_alpha(),
    "PinkSlimeDeadRight": image.load("Textures\png\Enemies\PinkSlimeDeadRight.png").convert_alpha(),
    "water_top": image.load("Textures\png\Tiles\water_top.png").convert_alpha(),
    "water": image.load("Textures\png\Tiles\water.png").convert_alpha(),
    "flag_red" : image.load("Textures\png\Object\\flag_red.png"),
    "flag_blue" : image.load("Textures\png\Object\\flag_blue.png"),
    "castle" : image.load("Textures\\png\\Tiles\\castle.png").convert_alpha(),
    "castleCenter" : image.load("Textures\\png\\Tiles\\castleCenter.png").convert_alpha(),
    "castleCliffLeft" : image.load("Textures\\png\\Tiles\\castleCliffLeft.png").convert_alpha(),
    "castleCliffLeftAlt" : image.load("Textures\\png\\Tiles\\castleCliffLeftAlt.png").convert_alpha(),
    "castleCliffRight" : image.load("Textures\\png\\Tiles\\castleCliffRight.png").convert_alpha(),
    "castleCliffRightAlt" : image.load("Textures\\png\\Tiles\\castleCliffRightAlt.png").convert_alpha(),
    "castleLeft" : image.load("Textures\\png\\Tiles\\castleLeft.png").convert_alpha(),
    "castleMid" : image.load("Textures\\png\\Tiles\\castleMid.png").convert_alpha(),
    "castleRight" : image.load("Textures\\png\\Tiles\\castleRight.png").convert_alpha(),
    "lava_top" : image.load("Textures\\png\\Tiles\\lava_top.png").convert_alpha(),
    "lava_bottom" : image.load("Textures\\png\\Tiles\\lava_bottom.png").convert_alpha(),
    "Bat1": image.load("Textures\png\Enemies\Bat1.png").convert_alpha(),
    "gun" : image.load("Textures\png\Tiles\gun.png").convert_alpha(),
    "key_red": image.load("Textures\png\Object\keyRed.png").convert_alpha(),
    "key_green": image.load("Textures\png\Object\keyGreen.png").convert_alpha(),
    "key_yellow": image.load("Textures\png\Object\keyYellow.png").convert_alpha(),
    "lava": image.load("Textures\png\Tiles\lava_bottom.png").convert_alpha(),
    "lava_top": image.load("Textures\png\Tiles\lava_top.png").convert_alpha(),
    "lava_top": image.load("Textures\png\Tiles\lava_top.png").convert_alpha(),
    "bird1" : image.load("Textures\\png\\Enemies\\bird1.png")
}

idleStates = {
    "normal0" : image.load("Textures\png\Player\\normal.png"),
    "normal1" : image.load("Textures\png\Player\\normal.png"),
    "fireball0" : image.load("Textures\png\Player\\fireball.png"),
    "fireball1" : image.load("Textures\png\Player\\fireball.png"),
    "gun0" : image.load("Textures\png\Player\\gun0.png"),
    "gun1" : image.load("Textures\png\Player\\gun1.png"),
    "crouch0" : image.load("Textures\png\Player\\crouch0.png"),
    "crouch1" : image.load("Textures\png\Player\\crouch1.png"),
}